### ISSUE TITLE
Added template atOauth and have also added social login services but no buttons appear

### ISSUE THREAD

**Issue by sferoze** [meteor-useraccounts/ionic#11]
So I added the atOauth template into my login page and I see no login buttons. I have also configured my meteor app by adding facebook, twitter, and google login services. 

I checked the helpers and it gets the helpers from AccountTemplates.atOauthHelpers. 

Since I added the right services what else do I need to do? The docs don't specify that you need to do anything else. How do I get the social login buttons to appear??

**Comment by sferoze** [comment]
Well I figured this one out too! 

You have to include

```
Meteor.startup ->
  ServiceConfiguration.configurations.update { service: 'google' }, { $set:
    clientId: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    client_email: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    secret: 'XXXXXXXXXXXXXXXXXXXXXXXX' }, upsert: true
```

**Comment by splendido** [comment]
useraccounts definitely needs a better step-by-step documentation :(
