### ISSUE TITLE
restrictive versioning

### ISSUE THREAD

**Issue by bgrayburn** [meteor-useraccounts/ionic#12]
Thanks for this library, definitely simplifying my life. I'm getting the following error when using this library with the meteor dev (specifically the cordova-improvements) branch. Is there a way to ease this version restriction?

```
=> Errors while initializing project:         

While selecting package versions:
error: Conflict: Constraint less@1.0.11 is not satisfied by less 2.5.0-plugins.0_2.
Constraints on package "less":
* less@=2.5.0-plugins.0_2 <- top level
* less@1.0.11 <- useraccounts:ionic 1.11.1    
```

**Comment by splendido** [comment]
I should remove the LESS dependency for good!
the only .less file included in the project has only plain css content...

**Comment by bgrayburn** [comment]
awesome thanks!

**Comment by splendido** [comment]
Shipping with next release...

**Comment by bgrayburn** [comment]
@splendido thanks!
