### ISSUE TITLE
Publish permission with facebbok

### ISSUE THREAD

**Issue by iuraya** [meteor-useraccounts/ionic#14]
Hi,

I'm trying to request publish permission while login with facebook but I'm not getting any result. I've created a test app in facebbok and tryied this config:

Client:
Accounts.ui.config({
  requestPermissions: {
    facebook: ['publish_actions']
  }
});

Server:
ServiceConfiguration.configurations.remove({
    service: 'facebook'
});

ServiceConfiguration.configurations.insert({
    service: 'facebook',
    appId: '*****_',
    secret: '**_******'
});

The loginUrl that I can see in the browser console does not include the publish permission in the scope.

I'm I doing it right?

**Comment by iuraya** [comment]
Solved with the info in

"Add configurable options for 3rd party login services #179" of meteor-useraccounts/core

**Comment by splendido** [comment]
Yeah, it's a bit of a mess right now, but this is already implemented in the current code for v2.0.
Hopefully we'll have an alpha release soon ;-)
