### ISSUE TITLE
Changing the label type for atPwdForm input fields

### ISSUE THREAD

**Issue by jaskinn** [meteor-useraccounts/ionic#2]
Is there a way to override the atPwdForm template?

For example I would like to use 'item-floating-label' instead of 'item-stacked-label'

**Comment by splendido** [comment]
Hi @jaskinn,

It's a bit tricky but doable ;-)

Lets have a look at [this issue](https://github.com/meteor-useraccounts/core/issues/212) on the [core repo](https://github.com/meteor-useraccounts/core).

I'd suggest to override only the [atTextInput template](https://github.com/meteor-useraccounts/ionic/blob/master/lib/at_input.html#L5-20), while keeping the `atPwdForm` unchanged.

Another possibility is to prepare a PR which adds another configuration optioin to let the developer choose the label type ;-)
We might consider this for a next release...

Let me know if this is what you're looking for

**Comment by kevohagan** [comment]
I might have a look at doing a config option for labels, that would go
nicely with a polymer form template :)

On 9 January 2015 at 08:48, Luca Mussi notifications@github.com wrote:

> Hi @jaskinn https://github.com/jaskinn,
> 
> It's a bit tricky but doable ;-)
> 
> Lets have a look at this issue
> https://github.com/meteor-useraccounts/core/issues/212 on the core repo
> https://github.com/meteor-useraccounts/core.
> 
> I'd suggest to override only the atTextInput template
> https://github.com/meteor-useraccounts/ionic/blob/master/lib/at_input.html#L5-20,
> while keeping the atPwdForm unchanged.
> 
> Another possibility is to prepare a PR which adds another configuration
> optioin to let the developer choose the label type ;-)
> We might consider this for a next release...
> 
> Let me know if this is what you're looking for
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/meteor-useraccounts/ionic/issues/2#issuecomment-69303331
> .

## 

Kevin O'Hagan
@kevohagan
+0034685245319
Palma de Mallorca,
Spain

**Comment by splendido** [comment]
Hi @kevohagan, nice to see you here!

...don't tell me you're leaving semantic-ui for ionic ;-)

**Comment by kevohagan** [comment]
Happy new year!

hahah

well im keeping my options open!

but its true that i have been looking at better mobile solutions for
meteor,

more than ionic (even if @nwientge is doign an amazing job with meteoric
http://meteoric.github.io/)

i've been checking out web components and mostly polymer (
polymer-project.org)

On 9 January 2015 at 10:12, Luca Mussi notifications@github.com wrote:

> Hi @kevohagan https://github.com/kevohagan, nice to see you here!
> 
> ...don't tell me you're leaving semantic-ui for ionic ;-)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/meteor-useraccounts/ionic/issues/2#issuecomment-69309945
> .

## 

Kevin O'Hagan
@kevohagan
+0034685245319
Palma de Mallorca,
Spain

**Comment by splendido** [comment]
Happy new year Kevin!

...yeah, it makes sense!
I'll get back to you soon ;-)

**Comment by splendido** [comment]
What do we do we this?

...consider we now have support for custom input field templates!
See [this example](https://github.com/meteor-useraccounts/core/issues/273#issuecomment-73137378) and the documentation for the `template` option among the one available for [Form Fields Configuration](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#form-fields-configuration)
