### ISSUE TITLE
How to add/change attributes to atNavButton

### ISSUE THREAD

**Issue by rclai** [meteor-useraccounts/ionic#3]
I wanted to take the `button-clear` class out of the button.

**Comment by splendido** [comment]
You might need to overwrite the `atNavButton` template.
See [this post](https://github.com/meteor-useraccounts/core/issues/212#issuecomment-67810815) about how to use [aldeed:template-extension](https://atmospherejs.com/aldeed/template-extension) to go about this.

**Comment by rclai** [comment]
Ah okay np. Good job on this btw.

**Comment by splendido** [comment]
tnx!
