### ISSUE TITLE
How can I wrap the sign-in page in an ionic template?

### ISSUE THREAD

**Issue by rootedsoftware** [meteor-useraccounts/ionic#4]
How can I wrap the sign-in page in an ionic template? The login form is bunched up at the top, I'd like it to be centered vertically, ionic has a way to do this. I'm just not sure how to get to the sign-in template to wrap it. 

Thanks

**Comment by splendido** [comment]
you can specify the template to be used as a parameter of `AccountsTemplates.configureRoute`.
the one used by default is [fullPageAtForm](https://github.com/meteor-useraccounts/ionic/blob/master/lib/full_page_at_form.html).

**Comment by rootedsoftware** [comment]
Thanks for the quick response. useraccounts is taking me to a page to sign-in, but I don't know what route I should customize. I've tried these below, but I think I'm off. Can you fill in the blank here?
`AccountsTemplates.configureRoute('____', {});`

```
AccountsTemplates.configureRoute('ensureSignedIn', {
    path: '/sign-in',
    name: 'signIn',
    redirect: '/accounts',
    template: 'MyLogin'
});

AccountsTemplates.configureRoute('signIn', {
    path: '/sign-in',
    name: 'signIn',
    redirect: '/accounts',
    template: 'MyLogin'

});
```

**Comment by splendido** [comment]
it should be

``` javascript
AccountsTemplates.configureRoute('signIn', {
    path: '/sign-in',
    name: 'signIn',
    redirect: '/accounts',
    template: 'MyLogin'

});
```

with 

``` handlebars
<template name=MyLogin">
  <div class="some class">
    {{> atForm}}
  </div>
</template>
```

**Comment by rootedsoftware** [comment]
Ok, that is what I had tried, but it wasn't working because of my 

```
Router.onBeforeAction(function () {
  if(!Meteor.user()) {
    // if the user is not logged in, render the Login template
    this.render('Login');
  } else {
    // otherwise don't hold up the rest of hooks or our route/action function from running
    this.next();
  }
});
```

I changed that to this

```
Router.onBeforeAction(function () {
  if(!Meteor.user()) {
    // if the user is not logged in, render the Login template
    this.render('MyLogin');
  } else {
    // otherwise don't hold up the rest of hooks or our route/action function from running
    this.next();
  }
});
```

Works great now. Thanks

**Comment by splendido** [comment]
Are you aware of [ensureSignedIn](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#content-protection)?

**Comment by rootedsoftware** [comment]
Very nice, that works much better. Thanks

On Sat, Apr 18, 2015 at 3:18 AM, Luca Mussi notifications@github.com
wrote:

> Are you aware of ensureSignedIn
> https://github.com/meteor-useraccounts/core/blob/master/Guide.md#content-protection
> ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/meteor-useraccounts/ionic/issues/4#issuecomment-94143003
> .

## 

## Joshua Bechard

Learn to do right! Seek justice, encourage the oppressed.
Defend the cause of the fatherless,
plead the case of the widow.

## Isaiah 1:17

**Comment by splendido** [comment]
:+1:
